### ISSUE TITLE
`--no-source-maps` flag appears to be ignored during build in `1.10.1`

### ISSUE THREAD

**Issue by dsinni** [parcel-bundler/parcel#2079]
# 🐛 bug report

`--no-source-maps` flag appears to be ignored during build. This just started happening recently, so I'm assuming it started in either `1.10.0` or `1.10.1`.

## 🎛 Configuration (.babelrc, package.json, cli command)
CLI via npm script:

```sh
"build": "parcel build src/index.html -d dist --no-source-maps",
```

## 🤔 Expected Behavior

No source maps.

## 😯 Current Behavior

Source maps.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | `1.10.1`
| Node             | `10.10.0`
| npm/Yarn         | `npm` `6.3.0`
| Operating System | Windows 10

**Comment by levrik** [comment]
Also experiencing this issue.
It's notable that the source map gets created but not linked from the JS file.

**Comment by sami616** [comment]
Im also experiencing this 1.10.1.

**Comment by levrik** [comment]
Somehow this issue just disappeared yesterday, not sure why.

**Comment by HosseinAgha** [comment]
It seems this issue happens in `>=1.10.0`

**Comment by DeMoorJasper** [comment]
Fixed by #2089 ?

**Comment by booninite** [comment]
I'm still seeing this behavior on `1.11.0`

**Comment by remko** [comment]
I'm also running into this issue on 1.11.0. Can this be reopened?

**Comment by mrcoles** [comment]
I am still seeing this issue on parcel-bundler 1.11.0.

1. If I build with source maps, then `rm -r dist/` and build with `--no-source-maps`, then I still get source maps in `dist/`
2. If I then `rm -r .cache/ dist/` to remove both the cache and dist and build again with  `--no-source-maps`, then I get it without source maps

```bash
./node_modules/.bin/parcel --version
1.11.0
```

**Comment by wawhal** [comment]
You must remove the `.cache` directory to make the flags work as expected. The flag policy seems to be `flag-first`.

**Comment by DeMoorJasper** [comment]
Opened a new issue to track this further as we have a more specific view on why this is happening now.

Further discussion should be moved here: #2692

Thanks for the detailed reproduction steps @mrcoles
