### ISSUE TITLE
Parcel 2 doesn't detect changes in linked dependencies.

### ISSUE THREAD

**Issue by samuelgozi** [parcel-bundler/parcel#4332]
# 🐛 bug report

When working on a dependency locally by linking it, Parcel 2 doesn't detect changes and therefore doesn't rebuild. You also need to remove the cache manually in order for it to work on re-runs.

## 🎛 Configuration (.babelrc, package.json, cli command)

Package.json
```json
{
	"name": "parcel-tamplate",
	"version": "1.1.0",
	"description": "My personal Parcel Template",
	"main": "public/index.html",
	"source": "src/index.html",
	"author": "Samuel Elgozi <samu.elgozi@gmail.com>",
	"license": "none",
	"private": true,
	"scripts": {
		"dev": "parcel src/index.html",
		"build": "parcel build src/index.html"
	},
	"targets": {
		"main": {
			"includeNodeModules": true
		}
	},
	"devDependencies": {
		"@babel/plugin-proposal-class-properties": "^7.8.3",
		"babel-eslint": "^10.0.2",
		"eslint": "^6.0.1",
		"less": "^3.9.0",
		"parcel": "^2.0.0-alpha.3.2"
	},
	"dependencies": {
		"firebase-auth-lite": "^0.4.1"
	}
}

```

The commands I use:
```
parcel src/index.html
```

## 🤔 Expected Behavior

Like in version 1, Parcel should detect changes in linked dependencies, invalidate the cache and rebuild.

## 😯 Current Behavior

No changes are made, which require manual removal of `.parcel-cache` and then building again.

## 🔦 Context

I use Parcel to work on npm modules often. Without detecting the changes in linked packages there is no reason for me to use parcel. In fact, it becomes painful to do so...

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2 |
| Node             | v13.10.1|
| Yarn         |1.22.1
| Operating System | MacOs Catalina 10.15.3 |

**Comment by DeMoorJasper** [comment]
Could you create a repo with some instructions on how I'd reproduce this? Would help a lot in fixing this

**Comment by samuelgozi** [comment]
Ok, here you go: https://github.com/samuelgozi/Parcel2-issue-4332
Further instructions can be found in the repo's README file.

**Comment by DeMoorJasper** [comment]
@samuelgozi thanks for creating the repo, I can reproduce it pretty consistently, will try and figure out why it happens and hopefully fix it

**Comment by samuelgozi** [comment]
@DeMoorJasper Thank you!

**Comment by Kalaschnik** [comment]
I develop a local npm package and experience the same issue using the `npm link` functionality. Is there any news on this?

**Comment by devongovett** [comment]
This is because the file watcher only watches for changes in the project root. It would be somewhat hard to implement support for symlinks outside the project I think. If we implemented this in the watcher we'd need to somehow crawl the whole file system to detect symlinks in the first place which would be very slow. We could potentially do it by detecting files that resolve to symlinks as we build the asset graph and keep nodes in the request graph to track watch roots. Then we'd have to re-watch all of those on startup and invalidate each of them for changes as opposed to just the project root.

**Comment by ramirofages** [comment]
> 
> 
> This is because the file watcher only watches for changes in the project root. It would be somewhat hard to implement support for symlinks outside the project I think. If we implemented this in the watcher we'd need to somehow crawl the whole file system to detect symlinks in the first place which would be very slow. We could potentially do it by detecting files that resolve to symlinks as we build the asset graph and keep nodes in the request graph to track watch roots. Then we'd have to re-watch all of those on startup and invalidate each of them for changes as opposed to just the project root.
> 
> ([parcel-bundler/watcher#32](https://github.com/parcel-bundler/watcher/pull/32))

This was actually working in parcel 1. Currently I had to revert back to parcel 1 while keeping its dependencies in parcel 2 to correctly build as module.

**Comment by krnlde** [comment]
This issue keeps me from migrating to v2, too. I wonder how other developers handle this workspaces issue - also considering monorepos are now en vogue. We can't possibly be alone here @ramirofages

**Comment by krnlde** [comment]
You guys should have a look at #6039 regarding the yarn.lock / package-lock.json files. This probably solves the issue for you too.

**Comment by kristojorg** [comment]
That linked issue doesn't resolve this for me. I don't have a dangling yarn.lock file, just the one in my primary repository I'm working on. Linked dependency changes don't trigger a recompile, and it seems even restarting parcel and running it with `--no-cache` don't trigger a full rebuild. I have the delete `.parcel-cache` in order to have the changes picked up : /

**Comment by krnlde** [comment]
Afaik parcel can't look outside its start context so if you want to watch all workspaces in a workspace root you'll need to start parcel in that root. Did you do that? Be extra sure to not have any lock files inside any of the workspaces. Parcel unfortunately has no warning for that and will just silently fall back to the workspace scope instead of root scope, which took a lot of lifetime from me in the past the point where I wanted to quit my job and start a lumber business :D

**Comment by kristojorg** [comment]
I am trying to link a dependency that is located in a separate folder and repository on my machine, but installed via npm. The `node_modules/my-dep` folder does change when I update the linked dependency, but parcel doesn't seem to pick up the changes there. Do you know if there is a way to have it watch and rebuild node_modules as well?

**Comment by krnlde** [comment]
As long as the node_modules is inside the parcel start context it works. Again parcel picks its start context by probing all folders for .lock files starting with the most-inner one from your start path: `parcel serve workspaces/workspace-a/index.html` probes:

1. `workspaces/workspace-a/*.lock`
2. `workspaces/*.lock`
3. `*.lock`

wherever a lock file is found it will not recognize changes beyond that folder. Ever. And they are not planning to change that.

**Comment by kristojorg** [comment]
Yep I hear you, but let me be more explicit about my setup. I have:

```bash
project-a/
    src/                      # code lives here
    example/
        index.html       # no lockfile here, no package.json, no node_modules
    package.json      # here is my script "npm run example": "parcel example/index.html"
    package-lock.json
    node_modules/
        project-b/
project-b/                # linked to ^
    src/
    dist/
```

It is the linked project-b dependency which is changing and not triggering a rebuild inside project-a when I run `npm run example`. So what I'm trying to say is that this isn't an issue of a misplaced or extra `*.lock` file it seems.

**Comment by krnlde** [comment]
So its linked by `npm link` and not by workspace logic? I couldn't repeat myself more but: 

> wherever a lock file is found it will not recognize changes beyond that folder

Edit: also to clarify, parcel doesn't watch the node_modules (since its essentially a black hole), it watches source files and triggers a reload when they change.

**Comment by mischnic** [comment]
If `project-a` contains a lockfile or a `.git` directory, it will be the project root and only files inside of that are watched.

> Edit: also to clarify, parcel doesn't watch the node_modules (since its essentially a black hole), it watches source files and triggers a reload when they change.

No, it watches everything except for VCS directories and `.parcel-cache`:
https://github.com/parcel-bundler/parcel/blob/ff6b7b4e97f95d8aabe3a93c22ec30f96b0fbf15/packages/core/core/src/RequestTracker.js#L918-L920

**Comment by kristojorg** [comment]
Okay yes it is the "Edit" there that is my problem then. The confusing thing is that this did work with parcel v1. When I would `npm link` package-b, parcel would rebuild package-a whenever it changed. 

As mentioned, `project-a` does contain a lockfile and a `.git` directory, but `node_modules` are within that folder so I expected them to be watched, or at least not permanently cached when I restart with `npm run example`. I currently have to delete `.parcel-cache` in order for it to include the updated `node_modules`.

**Comment by krnlde** [comment]
Ah cool! Didn't know that. How about symlinks then?

**Comment by kristojorg** [comment]
@mischnic so it does appear that this is a legitimate bug and not intended behavior, then. Should `node_modules` possibly be excluded from being written to the `.parcel-cache`?

**Comment by mischnic** [comment]
> How about symlinks then?

"only files inside of that are watched" essentially ignores symlinks. This is mostly because the file watching APIs from the various OSs only fire change events for the actual parent directories and don't traverse through every symlink

So `node_modules` is watched, but `node_modules/symlinked-package/*` isn't

So this is more of a technical limitation at the moment, as explained in https://github.com/parcel-bundler/parcel/issues/4332#issuecomment-706837311 and not a design decision

> a legitimate bug and not intended behavior, then. Should node_modules possibly be excluded 

What do you mean? It intentionally watches node_modules so that updating dependencies and rerunning Yarn triggers a Parcel rebuild for changed files.

**Comment by kristojorg** [comment]
I see, thanks for the explanation. I wonder if it would be possible to make an option to explicitly tell parcel about a symlinked dependency you would like to be watched, as this does seem like it would be a common use case. 

> What do you mean? It intentionally watches node_modules so that updating dependencies and rerunning Yarn triggers a Parcel rebuild for changed files.

I meant should `node_modules` be watched but not cached, such that when you restart parcel it is reading `node_modules` fresh and not using a cached version. I don't think I totally understand the value of including `node_modules` files in the cache if they are not bundled. Seems like I'm missing something tho : )

**Comment by padcom** [comment]
This is really bad... Parcel 1 used to work with symlinked packages as already mentioned in this thread. Not being able to symlink packages basically means one needs to restart the bundler every single time a change is made to external package.

Imagine working on an app that has a thin shell and a number of libraries that deliver parts of the app in the form of components. Unless you go monorepo it is just not possible to do it with Parcel right now.

That's really a shame. I wanted to base my next set of projects on Parcel 2, after waiting for so long for it to go GA and now it turns out it has this limitation :(

Any idea about other bundlers that don't have that limitation?

**Comment by JanMisker** [comment]
A very hacky workaround I found: 

1. Run parcel with `--no-cache`,  and 
2. Whenever the locally linked packaged changes, save `package.json` to trigger a rebuild

But I definitely agree that this should just work, Create React App does pick up changes in packages that are added with `npm link ../../another-project` so that could be inspiration?

**Comment by xuqingkuang** [comment]
> A very hacky workaround I found:
> 
> 1. Run parcel with `--no-cache`,  and
> 2. Whenever the locally linked packaged changes, save `package.json` to trigger a rebuild
> 
> But I definitely agree that this should just work, Create React App does pick up changes in packages that are added with `npm link ../../another-project` so that could be inspiration?

Good workaround, attach my code for example:

```typescript
chokidar.watch(LINKED_DEPENDENCIES, {/* OPTIONS */}).on('all', () => {
    const projectPackagePath = path.resolve(PROJECT, 'package.json');
    const now = new Date();
    fs.utimes(projectPackagePath, now, now);
});
```

But there's a minor issue with the workaround, LINKED_DEPENDENCIES changed will trigger the whole page reload, not HMR.

**Comment by danmarshall** [comment]
@JanMisker thanks for the workaround idea.

> 2. Whenever the locally linked packaged changes, save `package.json` to trigger a rebuild

In my case, I have more than 2 levels of dependencies in a monorepo, and this technique only seems to work one level deep.

Parcel 1 "just worked" quite magically. Without this ability, Parcel 2 is a step back in productivity. I would not have updated if it weren't for the many security issues of Parcel1 's dependencies.

**Comment by nikoloza** [comment]
This is still an issue right?

I used to trigger reload (not hmr) by `nodemon` watching the symlinked repository and trigger `package.json` file change in the main one.

**Comment by gjermundgaraba** [comment]
I have the exact same issue. This works perfectly for other HMR systems I have worked with. I'm using Lerna to symlink in different components. In Vue for instance this works perfectly, but on a simple parcel page it doesn't catch up (And I have to reload with --no-cache all the time...). 
Parcel 2 is certainly not having a good DX story for this kind of setup.

**Comment by padcom** [comment]
Guys, is this still being considered if it will be changed? What's stopping you from fixing this problem?

**Comment by devongovett** [comment]
It's on [the roadmap](https://github.com/parcel-bundler/parcel/discussions/7345), but it will be a bit complex to implement. We somehow need to discover all of the watch roots as parcel builds a project for the first time. We also need to check them all on startup when building from cache.

In addition, we will have to figure out how to handle paths that are outside the project root. Parcel's cache is meant to be portable between machines, or if you move your project directory, but symlinks outside the project root break this.

Also, symlinks tend to break node_modules resolution. For example, if your project has a dependency on React, and you symlink another module which also has a dependency on React, you will get two copies of React in your build and it most likely won't work at runtime.

Speaking from personal experience in the past trying to symlink projects together, I would definitely not recommend a setup like this. It breaks many things, not just watching. Using yarn/npm workspaces is much better in basically every way.

**Comment by yume-chan** [comment]
> Using yarn/npm workspaces is much better in basically every way.

yarn/npm workspaces are still symlinks:

> Please note the fact that `/workspace-a` is aliased as `/node_modules/workspace-a` via a **symlink**.
>
> _https://classic.yarnpkg.com/lang/en/docs/workspaces/#toc-how-to-use-it_

> Automating the linking process as part of `npm install` and avoiding manually having to use `npm link` in order to add references to packages that should be symlinked into the current `node_modules` folder.
>
> _https://docs.npmjs.com/cli/v7/using-npm/workspaces_

This is the problem: Parcel 2 now doesn't work with most monorepo solutions. (In my experience, it can detect file content changes in a Rush monorepo, but not file creation/deletion)

**Comment by devongovett** [comment]
To be clear, symlinks are fine as long as they point within the project root directory. That is the case with most monorepos, e.g. those managed by yarn or npm workspaces. I personally use these in several projects with parcel and it works fine.

**Comment by padcom** [comment]
Yeah, well unfortunately it all breaks down when you have modules in
different repos and you use npm link which is the de facto standard way of
linking libs in JS projects.

W dniu czw., 6.01.2022 o 05:57 Devon Govett ***@***.***>
napisał(a):

**Comment by sangupta** [comment]
Another workaround based on [fswatch](https://github.com/emcrisostomo/fswatch) that I have started using to trigger parcel 2 rebuilds:

```sh
$ fswatch -o /path/to/local/dependency/dist/library.js 
    | xargs -n1 -I{} 
        cp /path/to/local/dependency/dist/* /path/to/project/node_modules/mylib/dist
```

Library is declared as `file` dependency in my `package.json`:

```json
"dependencies": {
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router-dom": "^5.3.0",
    "bedrock": "file:/Users/sangupta/git/mylibrary"
}
```

**Comment by ksjogo** [comment]
Does someone have an example with a working setup with npm workspaces? I tried setting up my new project with them, but still need to (re)start manually when referring to packages by name like:
```
import JSGDHost from '@kronbergerspiele/jsgdbridge'

```
Using a relative path works though
```
import JSGDHost from '../bridge'
```

**Comment by PhenX** [comment]
This issue is a true blocker, and I tend to regret having upgraded from parcel 1 because of this :( This is a PITA when working with workspaces now. Having builds that take 3 seconds instead of 4 is cool, but not when you need to stop, delete cache and rebuild.

I'm really hoping this issue (in the short term roadmap) is addressed quickly.

Also, thank you for this great bundler !

**Comment by karasma3** [comment]
I upgraded to Parcel 2 and i find it really inefficient to parcel build every time i do some changes due to parcel watch not working. In parcel 1 everything worked as expected.
I am using this command `parcel watch src/index.html`
Is there any news to this issue?

**Comment by padcom** [comment]
For the moment, I found a temporary solution when working with libraries. Instead of making it a build-time dependency, I have tried to use it as runtime dependency, using module federation. That way, the lib is a separate project that you deploy separately so the entire build process doesn't rely on linked `node_modules`

https://github.com/padcom/minimal-vue2-module-federation-example

I know this example doesn't use Parcel, but the idea is exactly the same.

**Comment by danmarshall** [comment]
In my case, I was able to make it work by moving the invocation of `parcel` to the project root. I also need to move my `index.html` page out of the `packages/app` directory to a folder off the root directory.

**Comment by devongovett** [comment]
If you are having problems, could you please explain your setup in more detail? Parcel 2 works fine with yarn workspaces for example. As long as the symlinks are within your project root (i.e. git repo), it should already work fine.

If you are symlinking outside, how do you set this up? Manual `npm link` or similar? Is this only temporary? Do you work with a team? How do you ensure all devs have the same setup? I feel that monorepos i.e. yarn/npm workspaces are the true solution here. Happy to eventually add support for watching outside the project root but there is complexity there and I want to understand why this issue gets so much attention. So, please help me understand your setups.

**Comment by PhenX** [comment]
Hello, @devongovett I made a repository to reproduce the issue I had : https://github.com/am-creations/parcel-issue-4332-symlink-watch

The project structure in this example is similar to our projects : /src/package.json and /vendor/whatever/package.json, so the "main" package.json file is not in the project root.

* I do work with a team
* The project uses internal libraries added via subtree or submodule
* The issue happens when applying changes to thes libraries
* All devs use NPM 7 / node 14 or 8 / node 16, the issue is the same
* We work on Windows

**Comment by devongovett** [comment]
Thanks. One question: why not place your package.json/package-lock.json in the root of your repo rather than inside src? That would solve this problem.

**Comment by PhenX** [comment]
That was an option I tried, but got issues as NPM has a inheritance mechanism that is a PITA because we use preinstall scripts : all modules in a directory inside the root execute the scripts, for example. And there are maybe issues I could not identify because I was blocked by the first issue.
And as that it worked fine with parcel 1, we structured all our projects like this.

**Comment by devongovett** [comment]
Would an option to set the project root explicitly via the CLI to override the inferred root based on the lockfile work for you? Watching outside the project root is much harder, but if you could set the project root manually that might be a reasonable workaround?

**Comment by PhenX** [comment]
If you think it could work, I'm OK with this. Even further, do you think the common root directory could be found automatically? If not, could this option be set in the targets?

**Comment by bminer** [comment]
Just like @devongovett suggested, I was thinking about adding a CLI option that explicitly sets the project root, although I have an inexplicable inkling that this solution might be fraught with odd corner cases.

Perhaps a better approach is a CLI option that allows one to explicitly specify folders to watch outside of the project root. The project root would still be automatically determined as it is presently.  Thoughts?

**Comment by devongovett** [comment]
The problem is it's not portable between machines. Every person on your team would need a different configuration potentially.

**Comment by bminer** [comment]
@devongovett - Agreed.  Portability across machines could be compromised a bit if one could specify arbitrary folders to watch.  Although playing devil's advocate, this at least allows users to do it.  I can foresee a situation where users want to watch changes for a dependency that is `npm link`-ed into a project root.  Many "hacks" like these are temporary while dependencies are still under heavy development.

Here's the most common use case, IMHO.  Imagine, for example, a Git repository with `backend`, `frontend`, and `common` folders.  The Parcel root project folder might be `frontend` (i.e. where `package.json` is located), but there might be isomorphic code shared between the `backend` and `frontend` inside of the `common` folder.  In this case, it would be nice if Parcel could listen for changes in the `common` folder, even though this is a sibling folder outside of the project root.

**Comment by PhenX** [comment]
@devongovett @bminer as I mentionned earlier, do you think it's a viable option to find all symlinks (maybe with a max count), and watch the target folders of these simlinks, it would not require any change depending on the platform, developers, etc.

**Comment by devongovett** [comment]
You'd have to traverse potentially across the entire file system to find them, which sounds slow.

**Comment by theopolisme** [comment]
Perhaps an opt-in flag?

In our case, @bminer's description matches our setup as well. Across developer machines, the relative directory structure is consistent, though the absolute location of course would vary:

- `./monorepo` <- pnpm workspace
  - `./apps`
    - `./app-1` <- Parcel root
    - `./app-2`
  - `./packages`
    - `./package-1`
    - `./package-2`
  
The use-case is the same; developers make a change to `package-1` and want it to live refresh `app-1`. Using pnpm, package-1 has been symlinked into app-1's node_modules. Right now, Parcel doesn't detect those changes.

**Comment by PhenX** [comment]
We have a similar setup too.

I may not know all the aspects of the watcher, and I'm certainly ignoring a lot, but I don't think the entire file system needs to be traversed, only the paths we need to resolve.

After having replaced all aliases, and resolved any ".." in paths ans such, when a "real path" is not the same as the path to resolve, we may consider it to have at least one symlink, and the common root between these two paths could be taken as a new directroy to watch.

**Comment by louisgv** [comment]
This issue is easy to fix if the path to watch is configurable. Basically, borg this line:

https://github.com/parcel-bundler/parcel/blob/de1569572ab681bb6e90d2b330d002b5df7947ea/packages/core/core/src/Parcel.js#L376

And assimilate it to accept another option from the initial option, which it parsed inside the resolve option:

https://github.com/parcel-bundler/parcel/blob/de1569572ab681bb6e90d2b330d002b5df7947ea/packages/core/core/src/resolveOptions.js#L33

In particularly, this line: https://github.com/parcel-bundler/parcel/blob/de1569572ab681bb6e90d2b330d002b5df7947ea/packages/core/core/src/resolveOptions.js#L68

can be made to handle another optional input from the initialOption that would override the "project root". Better yet, I think we should just separate the darn watcher's root from the projectRoot altogether - as in letting user specify a "watchRoot" and just use that in the parcel watcher instead.

**Comment by josheppinette** [comment]
Here to provide my project structure that would be helped by this functionality. I have an `example` directory in my npm library repo which provides a fully ready togo example project that uses the library. The library is included in the `example/package.json` as `file:..`. The library code is not auto updated due to parcel in `example` not traversing symlinks.

I am currently using this as a workaround:

```sh
$ ls dist/* | entr touch example/package.json
```

**Comment by jameslaneconkling** [comment]
FYI Parcel does support linked dependencies when building a monorepo when properly configured. The following setup should work

```
package.json
package-lock.json

**Comment by jameslaneconkling** [comment]
FYI while Parcel doesn't currently support global symlinks created via `npm link`, it does work fine when building a monorepo (cc @krnlde , @danmarshall , @yume-chan , @theopolisme ). The configuration is hard to get right and isn't documented super well. Here's a super minimal example:

```
.parcel-cache/
node_modules/
packages/
  |- package_a/
    |- index.html
    |- index.js
    |- package.json
  |- package_b/
    |- index.js
    |- package.json
package.json
package-lock.json
```
```json
// package.json
{
  "name": "root",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "npm run dev --workspace package_a"
  },
  "workspaces": [
    "packages/package_b",
    "packages/package_a"
  ]
}
```
```json
// packages/package_a/package.json
{
  "name": "package_a",
  "version": "0.0.1",
  "scripts": {
    "dev": "parcel index.html"
  },
  "dependencies": {
    "package_b": "*"
  },
  "devDependencies": {
    "parcel": "^2.7.0"
  }
}
```
```json
// packages/package_b/package.json
{
  "name": "package_b",
  "version": "0.0.1",
  "source": "index.js",
  "main": "index.js"
}
```

Make sure only the workspace root has a `package-lock.json` file and no packages do. Ditto only project root should have `node_modules/` and `.parcel-cache/` directories.

**Comment by padcom** [comment]
I can verify that the above setup works. I even made a 3rd dependency in the lib and all of it was nicely bundled all at once. Impressive! And _ALL_ that without a single line of configuration code for anything, with Vue.js SFCs, sass and the almighty typescript. Hallelujah!

**Comment by danmarshall** [comment]
@jameslaneconkling thanks for posting that setup! In my scenario, I have these differences:
* parcel is in root, not under `/packages/` since several projects need to invoke it (did not want multiple copies of it).
* sub-packages have lock files, for maintaining their own dependency chain security.

**Comment by jameslaneconkling** [comment]
@danmarshall the docs on this are a little sparse, but looks like doing the following from root

```
npm install parcel --save-dev --workspace package_a --workspace package_b
```

installs a single copy of parcel in `/node_modules` and updates `/packages/package_a/package.json`, `/packages/package_b/package.json`, and `/package-lock.json`. The root `/package-lock.json` should pin dependencies across all packages; can't think of a reason you'd need to have that tracked separately per package, but could be missing something.

npm's [workspace docs](https://docs.npmjs.com/cli/v9/using-npm/workspaces) seem to suggest as much: no dependencies are defined in the root `package.json`, and the `package-lock.json` file is _only_ created in root.

**Comment by louisgv** [comment]
The approach @jameslaneconkling outlined applies to those with parcels as their only bundler invoked at the project's root. It works because Parcel symlinks resolver works just fine.

The key issue here is that Parcel watcher will ignore any resolved symlink path that's outside of the project root. Bundling/building will work just fine, but watching will not.

**Comment by DanTheOrange** [comment]
I am having a very similar issue. We are using a workspace for convenience. The packages are standalone and have their own `.lock` files. The workspace is optional. Being able to specify the root would solve what seems to be a common problem.

Edit: We are "solving" the issue for now by temporarily removing the lock file and checking it back out before committing changes. This is a horrible workflow, but the one we've chosen so we can still use Parcel.

**Comment by danmarshall** [comment]
@DanTheOrange my scenario also has packages which have their own lock files. Thanks for the workaround.

**Comment by bminer** [comment]
This does not seem like a difficult feature to implement, and I think it would help a good number of folks. If those in charge of this project are up for such a change, I'd be happy to try my hand at a PR for this.

My suggested approach is to simply add a CLI flag to explicitly specify other paths to watch outside the project root. If the user does not explicitly specify any folders, the default behavior is the current one: only files within the project root are watched for changes. While not ideal for all use cases, I think this approach provides the most flexibility without changing existing behavior.

Thoughts?

**Comment by maxx0r** [comment]
@bminer wouldnt say its easy (i couldnt do it probably), but for me (and others here) it would be an amazing feature.

Maybe add a --include-workspaces flag, so we can hook onto the specced workspaces?

**Comment by Systemcluster** [comment]
I believe the core issue here is that symlinks are just not resolved, and it would be solved by simply resolving all paths to their canonical form. That would also match the behavior of other bundlers.

Adding a specific flag for specific directories would not help in cases like #7518.

**Comment by maxx0r** [comment]
But you could read the relative path from the package.json right?

**Comment by devongovett** [comment]
That's not the issue. Symlinks can still resolve to locations outside Parcel's project root, which is defined to be the nearest directory with a `yarn.lock` or `package-lock.json` file. So if those are not at your repo root, but you reference a file outside of this directory, it won't be watched.

Is there a reason not to put your lock file at the root of your repo?

**Comment by bminer** [comment]
@Systemcluster - [As discussed above](https://github.com/parcel-bundler/parcel/issues/4332#issuecomment-706837311), allowing Parcel to watch symlinks outside the project root is trickier to implement. Allowing users to specify additional paths to watch outside of Parcel's project root seems like a fair compromise - and it [sounds rather easy to do](https://github.com/parcel-bundler/parcel/issues/4332#issuecomment-1266148929). As many have mentioned, the "project root" means the folder containing the package lock file.

**Comment by rodrigo-nexudus** [comment]
This used to work without issue in V1 (parcel-bundler) just by adding a link in package.json of the main project. Any changes on the linked package caused a refresh. This has now been open for 3 years and it was something that worked flawlessly on the first version of Parcel. It's an incredibly useful feature when you're working on a library.

**Comment by bminer** [comment]
Wow it really has been 3 years! Like I've said, I'd be happy to open a PR to resolve this one if I can get some feedback from the devs that it's likely to be merged. If the devs explicitly don't want this feature, I don't want to waste my time.

Thoughts? @devongovett

**Comment by maxx0r** [comment]
I for one would be really happy with a fix. I've built a script in my webapp that copies on change, not really the solutions you want

**Comment by rodrigo-nexudus** [comment]
@bminer I don't see why at least giving developers an option through a flag as you suggested would be an issue, if respecting symlinks outside the project root as before is out of the question. In our case, the package I'm working on is a dependency on more than one in-house project, and is not an integral part of any of the parent projects. It doesn't make sense to build all as "workspaces" as the parent projects have no relation between them.

**Comment by tpompon** [comment]
I'm getting the same issue. Building a package and I have a demo app using Parcel 2 in an folder `example`, I don't want to mix my `.lock` files and I would like to be able to get the app refreshing when I apply changes on the package components.

**Comment by AmrAhmedA** [comment]
I run into this issue recently, the fact that it is standing for 3 years is amazing. unfortuntly, such limitition in parcel 2 makes it less productive when working with linked dependencies. 
Possible workaround I found is to refresh `package.json` for triggering new build. 
any convenient solution proposed so far?

**Comment by ThomasZeman** [comment]
I agree it would be great to have this fixed. My scenario seems even simpler:

some_root_dir/
│
├─ client/
│   ├─ index.html
│   ├─ package.json
│   ├─ package-lock.json
│   └─ client.js
│
└─ shared/shared.js


where client.js imports shared.js -- When I change client.js Parcel does its thing, updates the browser and life is good. When I updated shared.js nothing happens. So to me, the file-watching issue comes down to:
Parcel should watch all files referenced starting from index.html as entry point no matter which directories these are in.

**Comment by rowthan** [comment]
> I agree it would be great to have this fixed. My scenario seems even simpler:
> 
> some_root_dir/ │ ├─ client/ │ ├─ index.html │ ├─ package.json │ ├─ package-lock.json │ └─ client.js │ └─ shared/shared.js
> 
> where client.js imports shared.js -- When I change client.js Parcel does its thing, updates the browser and life is good. When I updated shared.js nothing happens. So to me, the file-watching issue comes down to: Parcel should watch all files referenced starting from index.html as entry point no matter which directories these are in.

some issue, any way to solve this problem?

**Comment by rowthan** [comment]
> I agree it would be great to have this fixed. My scenario seems even simpler:
> 
> some_root_dir/ │ ├─ client/ │ ├─ index.html │ ├─ package.json │ ├─ package-lock.json │ └─ client.js │ └─ shared/shared.js
> 
> where client.js imports shared.js -- When I change client.js Parcel does its thing, updates the browser and life is good. When I updated shared.js nothing happens. So to me, the file-watching issue comes down to: Parcel should watch all files referenced starting from index.html as entry point no matter which directories these are in.

@rodrigo-nexudus there is the case what we want. `example` serve by parcel is just a side part of parent lib dir. we just want limit all test or dev code in `example` dir. But it should be rebuild after file changed in `src`.
So it's a very important for us to listen the change from other dir.

**Comment by nullablemind** [comment]
@jteppinette Thanks for your message. https://github.com/parcel-bundler/parcel/issues/4332#issuecomment-1311704659
Thanks to you, at least I was able to fasten the crutch so that it all works fine.
I have added a script to watch files using [chokidar](https://www.npmjs.com/package/chokidar) and simply call a `touch package.json` when have a change.

The best I could do at the moment. Since inside the folder, there are still their dependencies with package-lock.json.

**Comment by jfcere** [comment]
I personally worked around this using `nodemon` and `concurrently` with npm scripts, this solution is not perfect but works for me so I thought it worth sharing.

```bash
npm i concurrently nodemon --save-dev
```

See `start` script below which will concurrently...
- watch my lib `src` folder and rebuild it when it changes (I use `rollup` to bundle my lib)
- link my local library to node_module (I use the old `linklocal` package but you can use `npm-link` for that step)
- and finally start the web page using `parcel`

```json
  "scripts": {
    "prestart": "rimraf .parcel-cache",
    "start": "concurrently \"npm run watch:lib\" \"npm run link:lib && npm run start:demo\"",
    "start:demo": "parcel demo/index.html --open",
    "build:lib": "rollup -c rollup.config.ts --configPlugin @rollup/plugin-typescript",
    "link:lib": "rimraf node_modules/my-lib && linklocal",
    "watch:lib": "nodemon -e ts --watch src --exec npm run build:lib",
  },
```
Hope that helps anyone!

**Comment by devongovett** [comment]
FYI, thanks for @jondlm, there is a new `--watch-root` CLI option to configure the root directory where the watcher listens which will be available in the next release. See #9424 for details.

**Comment by remifroger** [comment]
Thanks, it works for me with `--watch-dir`

I've the app and, outside, I've shared js files (assets dir).

app/
├─ src/client/js/index.js
├─ package.json
├─ package-lock.json
assets/js

The dir assets is installed with `npm i ../assets` in the app
Then I import my modules in the app/src/client/js/index.js, for example : `import { myFunc1, myFunc2 } from 'assets/js/map.js'`

And now with this config in the app/package.json and the new `--watch-dir` :
```
"scripts": {
  "build-watch": "parcel watch ./src/client/js/index.js --watch-dir ../assets --host localhost --no-cache --public-url ./ --dist-dir ./dist && npm cache clean --force",
  "start-watch": "nodemon ./src/server/app.js",
   "dev": "concurrently --kill-others \"npm run start-watch\" \"npm run build-watch\""
}
```
The HMR is working again, like in parcel1. I mean, if I make a change in my assets js files, the app rebuild automatically.

**Comment by everdimension** [comment]
For those having issues, I have created a CLI-tool that can help deal with local npm packages: [physical-link](https://github.com/everdimension/physical-link)

It's not parcel-specific, but it solves the problem of aliased packages not being watched. What it does is basically watch your package files and copy changes to the `node_modules` directory of the project where you're using that package.

It's a handy tool when you can't have a monorepo and develop your packages as separate projects, and use them in your other projects.

**Comment by zeel01** [comment]
I really hoped that when I Googled this issue I would find a solution. I went off on a tangent one night writing a bunch of utilities to simplify a project, then realized it made no sense for them to belong to that project instead of being somewhere I could share with other projects. So I pulled it out into its own package... and now Parcel ignores any changes I make to it because the linked package doesn't trigger the watcher.

**Comment by bminer** [comment]
Since `--watch-dir` is a good workaround, is it safe to close this issue?

**Comment by bradleat** [comment]
This still doesn't work for me with `parcel build --watch-dir` it sometimes works, but often doesn't after I've made a few changes.

**Comment by bradleat** [comment]
This still does not work for me when I do a `parcel build` in a monorepo using the latest version (2.12.0)

I am using a lerna monorepo and this is my full parcel command:

`NODE_ENV=development npx parcel build --no-autoinstall --no-optimize --target frontends --cache-dir ./.parcel-cache --watch-dir ../../,`

I didn't really want to setup a dev / watch command although I might now...

**Comment by bminer** [comment]
Interesting. I am doing something quite similar, and it seems to work fine: `parcel --watch-dir ../ index.html`

**Comment by zeel01** [comment]
I don't think `--watch-dir` even comes close to solving the original issue. If you use `npm link` to symlink a package into your project, Parcel doesn't follow the link. Adding `--watch-dir` to watch the linked package that's somewhere else on your machine (possibly not in the same parent directory as your project even) is at best a hacky work-around since you might need to resort to an absolute file path. But it also doesn't seem to work reliably anyway.

The entire purpose if `npm link` is so you can include a local version of a dependency that might be unrelated to the current project without replicating a specific directory structure. As such, the bundler should support the feature as it is intended to be used without need for a work-around. Even if `--watch-dir` is a workable work-around for some users, the core issue remains.

Personally, I think the original labeling of this as a bug was correct since it's a regression from Parcel 1. But even as a feature request, it's still more than valid and is not adequately satisfied by `--watch-dir`.

**Comment by bradleat** [comment]
I agree. However, this especially noticeable when using parcel build over parcel watch.

**Comment by bminer** [comment]
> I agree. However, this especially noticeable when using parcel build over parcel watch.

@bradleat  - Are you saying that `parcel build` does not detect changes to paths outside of the Parcel "project root?" Are you absolutely sure about this? I was under the impression that this issue is specific to `parcel watch` only.

**Comment by bradleat** [comment]
@bminer Yes. When I parcel build with the command above and have updated linked build files, they are sometimes not included in the build. I really can't figure out why it is sometimes. 

When watching, it will work.

**Comment by zeel01** [comment]
It seems like it just uses it's cached version since it doesn't detect that anything is changed. I'm constantly needing to use `rimraf` to clear the cache out and get it to rebuild.

**Comment by brianhelba** [comment]
@bminer In my experience with this bug, the problem was that Parcel watching didn't follow symlinks. If watching `..` coincidentally also included the real destination of the symlink, then everything might work, but other project layouts could still cause problems.

In my case, I wasn't using `npm link`, but I had some application code which depended on an associated library via [a local path](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#local-paths). On Linux, npm or Yarn Classic (I can't remember which 😕) would create a symlink within `node_modules`, which Parcel wouldn't follow.

I recall that I was able to bisect the origin of this bug to some refactor of how symlinks were resolved when traversing `node_modules`. At that point, I gave up and just used `--no-cache`. Sorry that I can't be more precise or certain, since this occurred for me several years ago.

**Comment by uglycoyote** [comment]
A lot of people on this thread are saying this worked properly under Parcel 1, so I'm curious why the regression happened?

@devongovett  commented on this issue that it would be difficult to implement proper file-watching for symlinked directories:

> It's on https://github.com/parcel-bundler/parcel/discussions/7345, but it will be a bit complex to implement. We somehow need to discover all of the watch roots as parcel builds a project for the first time. We also need to check them all on startup when building from cache.

How did Parcel 1 do this in such a way that it worked for people, and is there something fundamental about Parcel 2 that made it stop working?  Did Parcel 1 cast a wider net with its file watcher?   

And why is it complex to add the symlinked directories to the file watcher?  It seems relatively straightforward, that if node_modules contains a symlinked folder that it could expand the watch to that folder, assuming that symlinked folder is not already underneath the currently-watched folder.  (i.e. it could do this using nodejs's `fs.lstatSync(folder).isSymbolicLink()` and `fs.readlinkSync(folder)`, to test if it's a symlink and get the corresponding path).  

There's a lot of pushback on this thread saying that one should simply make a monorepo and everything would work fine.  But along with that comes the assumption that it's OK to put a package.json at the root of the monorepo, and to make the monorepo a webdev project.  In my case I do have what you might call a monorepo, but it's a massive monorepo of a multi-language project where the javascript/web code is a small minority which lives in a few disparate and far-flung places within that monorepo and it's not really OK to throw a package.json at the root and have a file-watcher watch the entire tree under the monorepo root.  What I'd like is to be able to do is symlink a webapp that lives at some deep place within the tree to a library that lives at a completely different place in the tree, and have parcel's file watcher watch both places, but not the entire tree.  

The `--watch-dir` option does help with this (thanks for implementing that) though I agree with what @zeel01 said that it's not a proper solution to have to ask the user to pass this on the command line, when Parcel should be able to know to watch the symlinked folders.
