### ISSUE TITLE
Parcel 2: Adding an inline <style> tag moves the bundled CSS to the top of <head>

### ISSUE THREAD

**Issue by Cristy94** [parcel-bundler/parcel#4882]
# 🐛 bug report

Previous discussion: https://github.com/parcel-bundler/parcel/discussions/4820

## 🤔 Expected Behavior

Bundled CSS is always added as last child in `<head>`.

```
<head>
	<link rel="stylesheet" href="https://www.example.com/some.css" />
        <style>html,body {background: #e9eaed;}</style> 
        <link rel="stylesheet" href="/bundle.22506e2f.css">
</head>
```

The bundled CSS is no longer at the end of the `<head>` tag, so `some.css` would overwrite it.

## 😯 Current Behavior

Bundled CSS is imported as **first child**:
```
<head><link rel="stylesheet" href="/bundle.22506e2f.css">
	<link rel="stylesheet" href="https://www.example.com/some.css" />
        <style>html,body {background: #e9eaed;}</style>
</head>
```

## 💁 Possible Solution

Not sure why this happens, maybe it tries to add the bundle before the inline styles, which might be ok, but it shouldn't add it before all the other nodes in head.

## 🔦 Context

I can't overwrite library CSS as the bundled stylesheet is imported before those extenral CSS files.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.286

**Comment by mischnic** [comment]
What do the input HTML/JS file(s) look like?

**Comment by Cristy94** [comment]
Actually, I think it's just having the `index.js` importend in the body instead of the head:

index.html:

```HTML
<html>
<head>
	<link rel="stylesheet" href="https://www.example.com/some.css" />
</head>
<body>
    <h1>Hey</h1>
    <script src="index.js"></script>
</body>
</html>
```

index.js
```JS
import "/styles/test.css";
```

test.css
```CSS
body {
    background: red;
}
```

Output:

```
<html>
<head><link rel="stylesheet" href="/index.22506e2f.css">
	<link rel="stylesheet" href="https://www.example.com/some.css">
</head>
<body>
    <h1>Hey</h1>
    <script src="/index.2c77b0be.js"></script>
</body>
</html>
```

Not sure why sometimes the `<style>` tag triggered this problem, but now it seems that having the JS entry point in body is the problem.

**Comment by Cristy94** [comment]
Not related, but as a side note, even with this simple example, after moving the entry point from `<head>` to <body>` parcel kept crashing with this error until I cleared the cache:

```
Error: Got unexpected null
    at nullthrows (C:\wamp64\www\test-parcel\node_modules\nullthrows\nullthrows.js:7:15)
    at Asset.get publicId [as publicId] (C:\wamp64\www\test-parcel\node_modules\@parcel\core\lib\public\Asset.js:202:36)
    at C:\wamp64\www\test-parcel\node_modules\@parcel\reporter-dev-server\lib\HMRServer.js:102:19
    at Array.map (<anonymous>)
    at HMRServer.emitUpdate (C:\wamp64\www\test-parcel\node_modules\@parcel\reporter-dev-server\lib\HMRServer.js:83:50)
    at Object.report (C:\wamp64\www\test-parcel\node_modules\@parcel\reporter-dev-server\lib\ServerReporter.js:125:21)
    at ReporterRunner.report (C:\wamp64\www\test-parcel\node_modules\@parcel\core\lib\ReporterRunner.js:73:31)
    at async Parcel.build (C:\wamp64\www\test-parcel\node_modules\@parcel\core\lib\Parcel.js:383:7)
    at async Parcel.startNextBuild (C:\wamp64\www\test-parcel\node_modules\@parcel\core\lib\Parcel.js:272:21)
    at async PromiseQueue._runFn (C:\wamp64\www\test-parcel\node_modules\@parcel\utils\lib\PromiseQueue.js:98:7) {
  framesToPop: 1
}
```

This can always be reproduced in a few seconds: just move a few times the `<script>` from body to `<head>` and maybe also update the `index.js` once or twice. This also happens in the latest nightly version (333).

**Comment by mischnic** [comment]
> Parcel now keeps crashing until cache is cleared.

Yes, already fixed. Wait for the next nightly

**Comment by Cristy94** [comment]
Can you confirm that the example above reproduces the issue on your machine?

**Comment by mischnic** [comment]
Yes

Your example
```html
<html>
	<head>
		<link rel="stylesheet" href="https://www.example.com/some.css" />
	</head>
	<body>
		<h1>Hey</h1>
		<script src="index.js"></script>
	</body>
</html>
```
shoud behave like
```html
<html>
	<head>
		<link rel="stylesheet" href="https://www.example.com/some.css" />
		<script src="index.js"></script>
	</head>
	<body>
		<h1>Hey</h1>
	</body>
</html>
```

which already correctly inserts the link after the existing one:
```html
<html>
	<head>
		<link rel="stylesheet" href="https://www.example.com/some.css" />
		<link rel="stylesheet" href="/index.2ccae8b1.css" />
		<script src="/index.b1eda6b3.js"></script>
	</head>
	<body>
		<h1>Hey</h1>
	</body>
</html>
```

**Comment by Cristy94** [comment]
Any progress on this? The order of CSS imports is really important.

**Comment by euljr** [comment]
I have the same issue and I think I found the reason for this to happen.

https://github.com/parcel-bundler/parcel/blob/413a09364646811f6067be80065c15d7b6270236/packages/packagers/html/src/HTMLPackager.js#L231

The function `findBundleInsertIndex` defaults to the first position when it can't find neither the `doctype` (which doesn't exists inside the `head` tag) nor a `non-metadata` tag.

By changing the line to fallback to the last position should fix the issue, something like:

```js
  return doctypeIndex ? doctypeIndex + 1 : content.length;
```

What do you think? I can open a PR but I would need help to figure out if this can have a negative impact somewhere else.

**Comment by Cristy94** [comment]
> nor a non-metadata tag

Are you saying that I can somehow force the bundled CSS to be added after a specific tag (before the fix is implemented)?
A fix would be greatly appreciated as I still have the same issue for a year, I can't overwrite material-icons font size in my SASS files.

**Comment by euljr** [comment]
> Are you saying that I can somehow force the bundled CSS to be added after a specific tag (before the fix is implemented)?

It's not ideal but, right now if you add a `<span></span>` inside the `<head>` in your main html file, the `link` tag will be inserted before it.

The result will be something like:

```html
<head>
	<link rel="stylesheet" href="https://www.example.com/some.css" />
        <style>html,body {background: #e9eaed;}</style> 
        <link rel="stylesheet" href="/bundle.22506e2f.css"> <!-- HERE -->
        <span></span>
</head>
```

Edit.: Not just span, but [any tag other than `base`,  `link`,  `meta`,  `noscript`,  `style`,  `template` and `title`
](https://github.com/parcel-bundler/parcel/blob/413a09364646811f6067be80065c15d7b6270236/packages/packagers/html/src/HTMLPackager.js#L18)

**Comment by Cristy94** [comment]
So adding an empty `<script>` should be both valid and maintain the order. I will test it, thanks!

**Comment by euljr** [comment]
> So adding an empty `<script>` should be both valid and maintain the order.

Absolutely! I didn't notice that the `<script>` was commented when skimming.

I'll try to open a PR in the next few days, still haven't got the time just yet.

**Comment by mischnic** [comment]
A PR would be great! Here are the related test cases we currently have. I remember adding the last two tests listed here when I added the `doctypeIndex`-related logic, so duplicating and modifying one of them should work.

https://github.com/parcel-bundler/parcel/blob/8d50ec65914803bdc1ba8e719d27fcd833422839/packages/core/integration-tests/test/html.js#L221

https://github.com/parcel-bundler/parcel/blob/8d50ec65914803bdc1ba8e719d27fcd833422839/packages/core/integration-tests/test/html.js#L252

https://github.com/parcel-bundler/parcel/blob/8d50ec65914803bdc1ba8e719d27fcd833422839/packages/core/integration-tests/test/html.js#L318

https://github.com/parcel-bundler/parcel/blob/8d50ec65914803bdc1ba8e719d27fcd833422839/packages/core/integration-tests/test/html.js#L1618

https://github.com/parcel-bundler/parcel/blob/8d50ec65914803bdc1ba8e719d27fcd833422839/packages/core/integration-tests/test/html.js#L1673
