### ISSUE TITLE
Errors should tell me _where_ the error is

### ISSUE THREAD

**Issue by surma** [parcel-bundler/parcel#5470]
# 🐛 bug report

I get errors stating a problem, but not where it was encountered.

```
$ npx parcel build index.html things/**/index.html 
```

![Screen Shot 2020-12-14 at 11 29 24](https://user-images.githubusercontent.com/234957/102076561-cb32f000-3dff-11eb-9895-eae52d328e1d.png)
(This one was a left-over unpkg.com import in a JS file)

![Screen Shot 2020-12-14 at 11 29 29](https://user-images.githubusercontent.com/234957/102076572-ce2de080-3dff-11eb-83e2-ad57451f13e2.png)
(This one was in a SVG file. Gonna file another bug for this)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1
| Node             | v14.9.0
| npm/Yarn         | npm@6.14.9
| Operating System | MacOS 10.15.7

**Comment by mischnic** [comment]
> (This one was in a SVG file. Gonna file another bug for this)

This might already be fixed in the nightly: https://github.com/parcel-bundler/parcel/pull/5188

**Comment by surma** [comment]
I see that a PR was merged to fix this for unknown pipelines. But I just got this error, so I am wondering if there is something that could be done more generally to show which file was being processed to cause an error? 

![Screen Shot 2020-12-14 at 16 02 25](https://user-images.githubusercontent.com/234957/102104182-c84af600-3e25-11eb-8a2d-36a12c6782f7.png)

**Comment by mischnic** [comment]
Generally, we try to do this for user-facing errors anyway (in the pipeline case, it was just an oversight so we fix this on a case-by-case basis because the general architecture for generating code-frames and such is already implemented).

But this error is either caused by a malfunctioning plugin or a Parcel bug (probably the same as https://github.com/parcel-bundler/parcel/issues/5311). You probably expected a file path to be printed? One problem is also that file paths don't uniquely identify assets...

**Comment by surma** [comment]
![Screen Shot 2020-12-14 at 16 45 19](https://user-images.githubusercontent.com/234957/102109295-cd12a880-3e2b-11eb-9a1d-8e90d226ee9e.png)

Another one. It tells me line and character, but _not_ which file. 

> But this error is either caused by a malfunctioning plugin or a Parcel bug (probably the same as #5311). You probably expected a file path to be printed? 

I don’t know — I guess that’s kind of the problem. Fwiw, unlike #5311, deleting `.parcel-cache` didn’t solve the issue here for me.

**Comment by mischnic** [comment]
> that could be done more generally

Alright, I'm convinced 😄  -> https://github.com/parcel-bundler/parcel/issues/5477

> deleting .parcel-cache didn’t solve the issue here for me.

Any chance you can post a reproduction?
