### ISSUE TITLE
🐛 SVG <defs>, <symbol> and <use> are unsupported in parcel build

### ISSUE THREAD

**Issue by alyssaq** [parcel-bundler/parcel#703]
🐛 bug report 
support SVG `<defs>`, `<symbol>` and `<use>` in HTML

### 🤔 Expected Behavior
SVG `<defs>`, `<symbol>` and `<use>` tags to be present in the output minified html file.

### 😯 Current Behavior
Ive been able to consistently reproduce the problem in one `index.html` file:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg">
      <defs>
        <g id="circle">
          <circle cx="100" cy="100" r="100"/>
        </g>
      </defs>
    </svg>
    <div id="app">
      <svg style="display:block;margin:0 auto;" height="250px">
        <use xlink:href='#circle' href='#circle'/>
      </svg>
    </div>
  </body>
</html>
```
run: ` parcel build index.html`

output: 
```
<!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> </head> <body> <svg xmlns="http://www.w3.org/2000/svg"/> <div id="app"> undefined </div> </body> </html> 
```

The `<defs>` tag disappears and `<use>` tag is replaced with `undefined`.
Note that I use xlink:href as href is not supported in Safari 11

### 💁 Possible Solution

Using `<svg>` works and is transpiled correctly. I could omit the use of `<defs>` and move the entire `<svg>` content to all the places I have the `<use>` tag. Sadly, as you'll notice, that'll mean having repeated svgs which `<defs>` were created to solve.

### 🔦 Context

I define my re-usable svgs in `<defs>` or `<symbol>` in index.html and use them throughout my application.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.5.1
| Node             | 9.4.0
| npm        | 5.6.0
| Operating System | macOS High Sierra
| Browsers|Safari 11.0.1, Chrome 63.0.3239.132

**Comment by DeMoorJasper** [comment]
This is probably related to #578 and #544 , probably an issue related to https://github.com/posthtml

**Comment by alyssaq** [comment]
I dug a little deeper and found the point where the AST went wrong: https://github.com/parcel-bundler/parcel/blob/master/src/transforms/posthtml.js#L12

`posthtml` parsed it correctly but the minifier `htmlnano` built an incorrect AST of `index.html`. Heres a little script that verifies this:
```js
const posthtml = require('posthtml')
const htmlnano = require('htmlnano')

const html = `
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg">
      <defs>
        <g id="circle">
          <circle cx="100" cy="100" r="100"/>
        </g>
      </defs>
    </svg>
    <div id="app">
      <svg style="display:block;margin:0 auto;" height="250px">
        <use xlink:href='#circle' href='#circle'/>
      </svg>
    </div>
  </body>
</html>
`

const result = posthtml()
  .process(html, { sync: true })
  .html
console.log(result)

const options = {
  collapseWhitespace: 'conservative'
}
htmlnano.process(html, options).then((result) => {
  console.log(JSON.stringify(result.tree[3]))
})
```
posthtml output:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg">
      <defs>
        <g id="circle">
          <circle cx="100" cy="100" r="100"></circle>
        </g>
      </defs>
    </svg>
    <div id="app">
      <svg style="display:block;margin:0 auto;" height="250px">
        <use xlink:href="#circle" href="#circle"></use>
      </svg>
    </div>
  </body>
</html>
```
htmlnano output (defs and use tag are gone):
```
{"tag":"html","attrs":{"lang":"en"},"content":[" ",{"tag":"head","content":[" ",{"tag":"meta","attrs":{"charset":"utf-8"}}," "]}," ",{"tag":"body","content":[" ",{"tag":false,"attrs":{},"content":"<svg xmlns=\"http://www.w3.org/2000/svg\"/>"}," ",{"tag":"div","attrs":{"id":"app"},"content":[" ",{"tag":false,"attrs":{}}," "]}," "]}," "]}
```

I looked in `htmlnano` and the problem seems to be `SVGO`. If I disable svg minification, it works.
```
const options = {
  collapseWhitespace: 'conservative',
  minifySvg: false
}
```

**Comment by DeMoorJasper** [comment]
@alyssaq could u report this to either `htmlnano` or `svgo`? as this appears to be an issue that should get resolved with either of these projects.
Minifysvg should minify not remove the svg so this is a bug with one of these projects not with parcel

**Comment by alyssaq** [comment]
Ha, its my fault. I ran each snippet of the svg in `svgo` and got this error:
`{ error: 'Error in parsing SVG: Unbound namespace prefix: "xlink"\nLine: 0\nColumn: 98\nChar: >' }`

I added the `xlink` prefix to the `svg` tag:
```
<svg xmlns:xlink="http://www.w3.org/1999/xlink" style="display:block;margin:0 auto;" >
     <use xlink:href='#circle' href='#circle'/>
</svg>
```

`parcel build index.html` correctly outputted the svg!

Learnt something new about svg.     
Thanks for responding so quickly. 😄

**Comment by davidenke** [comment]
@alyssaq after a quick research at [the specs](https://www.w3.org/TR/SVG/struct.html#UseElementHrefAttribute) it looks like both attributes are required `xmlns` *and* `xmlns:xlink` at the `svg` element.
```svg
<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink"
>
    <use xlink:href="assets/sprite.svg#icon"></use>
</svg>
```
Now my IDE (IntelliJ) shows no more warnings.

**Comment by speigg** [comment]
This is still broken. Parceljs is modifying my html-embedded SVG...

**Comment by speigg** [comment]
Please re-open

**Comment by yw662** [comment]
@speigg A quick work around: pass `--no-minify` to `parcel build`, or move your inline svg standalone.

This is designed behavior of `posthtml`, which calls `htmlnano` as minifier, which calls `svgo` to minify your inline svg.

**Comment by MattIPv4** [comment]
Also still seeing this with SVG symbols which are then being used later in a HTML file. Disabling minification fixed this, but it'd be great to see a proper fix.

**Comment by devongovett** [comment]
Please file an issue with htmlnano.

**Comment by randol1k** [comment]
Not sure if my issue is related to this topic, but Parcel 2.0.0 beta 2 is cutting off the following code:

Before npm run build:
```
<svg>
    <use href="file.svg#icon-search" />
</svg>
```

After npm run build:
```
<svg>
    <use href="file.svg" />
</svg>
```
Thus, SVG icons are not shown in a browser. If I put manually #icon-search in the Inspector, they show up. I also disabled minifier by adding parcel build --no-optimize, but result is the same, it just cuts off #icon-search.

Can someone advise?

**Comment by mischnic** [comment]
That's the same problem as https://github.com/parcel-bundler/parcel/issues/6048

**Comment by randol1k** [comment]
> That's the same problem as #6048

Thank you for a reply, yes, the behaviour looks the same, but the issue is the guy has a problem with "a" element and data-anchor works for him, but in my case it's "use" element and while I tried to do the following:

```
<use
    href="src/img/icons.svg"
    data-anchor="#icon-search"
></use>
```

Nothing happened on my side, unfortunately

**Comment by mischnic** [comment]
This behaviour occurs anytime Parcel take a URL and resolves to another file.

And in that other issue, another build step outside of Parcel was added that uses `data-anchor` to re-add that hash: https://github.com/parcel-bundler/parcel/issues/6048#issuecomment-808597733

**Comment by randol1k** [comment]
> This behaviour occurs anytime Parcel take a URL and resolves to another file.
> 
> And in that other issue, another build step outside of Parcel was added that uses `data-anchor` to re-add that hash: [#6048 (comment)](https://github.com/parcel-bundler/parcel/issues/6048#issuecomment-808597733)

I see now, so it's like a variable to be added to each svg link upon building process.

Thank you
