### ISSUE TITLE
[Bug] HMR and PostCSS modules, styles disappear

### ISSUE THREAD

**Issue by pavel** [parcel-bundler/parcel#809]
🐛 bug report

### 🎛 Configuration

.babelrc
```json
{
	"presets": [
		"react",
		["env", {
			"targets": {
				"browsers": [ "last 2 versions" ]
			},
			"debug": true
		}]
	]
}
```

.postcssrc.js
```js
module.exports = {
	modules: true,
	plugins: {
		"autoprefixer": {}
	}
};
```

browserslist
```
last 2 versions
```

index.html
```html
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>React App</title>
	</head>
	<body>
		<div id="app"></div>

		<script src="./index.js"></script>
	</body>
</html>
```

index.js
```js
require("babel-polyfill");

const styles = require("./app.styl");

console.log("styles???", styles);

const React = require("react");
const ReactDOM = require("react-dom");

const App = () => (
	<div className={ styles.app }>Hello!!</div>
);

ReactDOM.render(<App/>, document.getElementById("app"));
```

app.styl
```styl
.app
	color: blue
	transform: scale(0.95)
	transition: transform 0.4s ease
```

CLI: `./node_modules/.bin/parcel index.html`

### 🤔 Expected Behavior

Changing `app.styl` should update styles properly.

### 😯 Current Behavior

Styles disappear after change to `app.styl`.
`index.js` (which requires `app.styl`) is not reloaded when the `app.styl` file is changed.

### 💻 Code Sample

Source code: 
[parcel-postcss-modules-bug.tar.gz](https://github.com/parcel-bundler/parcel/files/1725533/parcel-postcss-modules-bug.tar.gz)

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.5.1 and `master` at 6deec80b3491dc5ac690da6550323b51deec6530
| Node             | 9.5.0
| npm         | 5.6.0
| Operating System | Linux x86_64

**Comment by yiooxir** [comment]
Have the same issue

**Comment by joakin** [comment]
I think I've hit this issue with a typescript + css modules repo. See https://github.com/joakin/parcel-bundler-test/ for minimal example.

Here's a gif that shows the broken behavior:

![parcel-css-modules](https://user-images.githubusercontent.com/657839/37651874-e34d1e2a-2c39-11e8-96f8-264836646d30.gif)

On reload it also shows that the styles object is broken (seems like it takes the old hashes and uses them as keys)

When doing `parcel build` it seems to work fine and generate the correct CSS file.

**Comment by joakin** [comment]
#644 seemed related, but I've tried changing the `.postcssrc.js` to this:

```js
module.exports = {
  modules: true,
  plugins: {
    "postcss-modules": {
      generateScopedName: "_[path]_[name]__[local]"
    }
  }
};
```

And it still doesn't work. The first hot reload works, but after that the class names seem to break. Going to try without hmr and see.

**Comment by joakin** [comment]
Running `parcel src/index.html --no-hmr` the issue persists across reloads. The postcss modules support seems to be broken, unrelated to HMR.

**Comment by aelsv** [comment]
Have this issue 2. Any updates?

**Comment by aelsv** [comment]
Ok. Seems like i fixed this for me.
Try it.
`{
  "modules": true,
  "plugins": {
    "postcss-modules": {
      "generateScopedName": "[name]_[local]_[hash:base64:5]"
    },
    "autoprefixer": {
      browsers: [
        "> 1%",
        "Last 2 versions"
      ]
    }
  }
}
`

**Comment by joakin** [comment]
I tried that exact config, didn't work for me on that repo example.

```
=> npm ls postcss-modules
└── postcss-modules@1.1.0

=> npm ls parcel-bundler
└── parcel-bundler@1.6.2
```

**Comment by joakin** [comment]
I've checked with normal CSS, and there is funny business too, even just by plain reloading with `--no-hmr`. I'm not sure what is even going on, here is the code...

https://github.com/joakin/parcel-bundler-test/tree/normal-css

And the change I made [035d84](https://github.com/joakin/parcel-bundler-test/commit/035d844b9f84298233f0a49448f46acb81e8cd9e)

Hopefully the test repo is small enough to help reproduce

**Comment by JoeLanglois** [comment]
Same thing on my end... only thing keeping me from using Parcel atm.

**Comment by ilogico** [comment]
This is cause by the class names being _remangled_.
For example, a css file with
```css
.main {
    color: blue;
}
```
exports the object:
```javascript
{
    main: '_main_qaqe8_1'
}
```

Changing the original file will make the exported module to be:
```javascript
{
    _main_qaqe8_1: '__main_1eufg_1_1eufg_1'
}
```
So `style.main` will be undefined and the elements stop having classes.

I took a quick glance at the code, but I can't find the problem. Maybe the issue is with postcss-modules itself.

**Comment by BipinBhandari** [comment]
Whenever changes are made, stylesheet file is updated with new classname but html is not updated and old class name remains in it. If we could find a way to update classnames in html, this issue would be solve.

**Comment by joakin** [comment]
Shouldn't the JS file be recompiled too since the dependent module (CSS)
changed?

**Comment by BipinBhandari** [comment]
@joakin I just tested it and change in scss file is not recompiling JS

**Comment by BipinBhandari** [comment]
Finally I was able to solve this issue by adding this on plugins in `.postcssrc` 
```
    "postcss-modules": {
      "generateScopedName": "[name]_[local]_[hash:base64:5]"
    }
```

`.postcssrc` now looks like 

```
{
  "modules": true,
  "plugins": {
    "autoprefixer": {
      "grid": true
    },
    "postcss-modules": {
      "generateScopedName": "[name]_[local]_[hash:base64:5]"
    }
  }
}
```
@aelsv also seems to have suggested this solution. thanks @aelsv

**Comment by DeMoorJasper** [comment]
So this appears to be a mis-configuration can this be closed?

**Comment by pavel** [comment]
Not a misconfiguration.
@BipinBhandari has managed to hack around it.

**Comment by lukebarton** [comment]
@pavel Can you explain what about @BipinBhandari 's configuration is problematic?

**Comment by joakin** [comment]
It is not a configuration problem. When a JS file depends on a CSS file that uses post-css modules, and the CSS file changes, the JS file doesn't get recompiled.

See the parcel docs: https://parceljs.org/transforms.html#postcss With those instructions parcel doesn't work with hmr which is the default mode.

@lukebarton I have a very simple SSCCE here: https://github.com/joakin/parcel-bundler-test

Steps to see the bug are:

1. npm start
2. Open localhost:1234
3. Edit App.css and change the text color

**Expected**: Text color changes in the browser

**Actual**: class name is mangled and all styles are lost. Not even refreshing works.

---

I have also tried with `generateScopedName` in the config, and it **doesn't** work for me sadly. Check out the `fixed-postcss-classnames` branch on that same repo: https://github.com/joakin/parcel-bundler-test/blob/fixed-postcss-classnames/.postcssrc.js

---

Let me know if there is anything else I could do to help diagnose. I've updated the repo to the latest parcel and all deps.

**Comment by pavel** [comment]
@lukebarton Exactly what @joakin described.
@BipinBhandari configuration is not problematic, it is that `parcel` should work with the default config as in docs.

**Comment by maxholman** [comment]
@joakin and anyone else using `.postcssrc.js` and `generateScopedName` - you can `Object.freeze` your `plugins` to get this working.

Parcel actually deletes your original configuration (presumably unintentionally) after the initial build, so it's not used for any subsequent builds.

Using `Object.freeze` prevents the internal `delete config.plugins['postcss-modules']` call from achieveing anything, and doesn't throw an error.

```
module.exports = {
  modules: true,
  plugins: Object.freeze({
    "postcss-modules": {
      generateScopedName: "_[path]_[name]__[local]"
    }
  })
};
```

**Comment by joakin** [comment]
I've tried that suggestion on https://github.com/joakin/parcel-bundler-test/blob/fixed-postcss-classnames/.postcssrc.js and it didn't work at all for this sample repo: https://github.com/joakin/parcel-bundler-test ☹️

**Comment by joakin** [comment]
I've tried again with updated versions of everything (`"parcel-bundler": "^1.9.1"`, etc), still not working.

* Instructions followed: https://parceljs.org/transforms.html#postcss
* Repro repo: https://github.com/joakin/parcel-bundler-test
* PostCSS config: https://github.com/joakin/parcel-bundler-test/blob/master/.postcssrc.js

```js
module.exports = {
  modules: true
};
```

Original problems still persist, see [comment with gif](https://github.com/parcel-bundler/parcel/issues/809#issuecomment-374563987).

**Comment by maxholman** [comment]
I'm now getting the same issue as you even with my previous suggested fix.

I've opened PR #1589 which stops `generateScopedName` from being deleted, and allows for a workaround for this issue.

You can try out my fork on that PR and use a `generateScopedName` config to see if it solves your issue.

**Comment by devongovett** [comment]
Fixed by #1589.

**Comment by joakin** [comment]
I've updated parcel to the latest release on [parcel-bundler-test](https://github.com/joakin/parcel-bundler-test/), and now:

* Only with `modules: true` in [.postcssrc.js](https://github.com/joakin/parcel-bundler-test/blob/master/.postcssrc.js) HMR is still broken, but
* Adding `generateScopedName` configuration now fixes it and HMR works. See [.postcssrc.js in the fixed-postcss-classnames branch](https://github.com/joakin/parcel-bundler-test/blob/fixed-postcss-classnames/.postcssrc.js)

I am not sure if it is the [PostCSS](https://parceljs.org/transforms.html#postcss) docs that need updating to include configuring `generateScopedName` or if this is something that should be fixed in the bundler itself being an issue with HMR.

In any case, leaving these comment as reference for others coming by with the same issue.

**Comment by yanisvieilly** [comment]
@joakin When I use `--no-hmr`, it works perfectly. When I don't, my CSS file and the references to its classes in my JS file are left intact. I tried your solution with `generateScopedName` and unfortunately, it doesn't work any better. ☹️
