### ISSUE TITLE
`Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/src/app/node_modules/lmdb/build/Release/lmdb.node)` in Alpine

### ISSUE THREAD

**Issue by hood** [parcel-bundler/parcel#8243]
# 🐛 bug report
Gettin the following error when trying to run `parcel build` under alpine linux (used to build a Docker container for my application)
```
Step 16/29 : RUN yarn build
 ---> Running in 90cb9271fd70
yarn run v1.22.18
$ parcel build trial/index.html && cp -r public/* dist
Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/src/app/node_modules/lmdb/build/Release/lmdb.node)
    at Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (/usr/src/app/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at load (/usr/src/app/node_modules/node-gyp-build/index.js:22:10)
    at Object.<anonymous> (/usr/src/app/node_modules/lmdb/dist/index.cjs:2257:47)
    at Module._compile (/usr/src/app/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'ERR_DLOPEN_FAILED'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn build' returned a non-zero code: 1
```

## 🎛 Configuration (.babelrc, package.json, cli command)
Excerpt from my Dockerfile
```dockerfile
# *INSTALLER*

FROM node:18-alpine as installer

RUN apk add --update gcc g++ make python3

# Create the application directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Copy files needed for installing dependencies
COPY package.json .
COPY yarn.lock .

RUN yarn install

# -----------------------------------------------------------------------------
# *BUILDER*

FROM node:18-alpine as builder

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Copy source files
COPY . .
COPY --from=installer /usr/src/app/node_modules/ .

ENV NODE_ENV=production

RUN yarn build
```

## 🤔 Expected Behavior
The project should build without errors, or documentation should be added in order to get my Docker deps right. 

## 😯 Current Behavior
See general description

## 💁 Possible Solution
N.A.

## 🔦 Context
N.A.

## 💻 Code Sample
N.A.

## 🌍 Your Environment
N.A.

**Comment by hood** [comment]
UPDATE:
"Fixed" this by installing `gcompat`. Now it segfaults instead :facepalm: .

**Comment by mischnic** [comment]
cc @kriszyp

**Comment by kriszyp** [comment]
@hood Here is my best attempt at reproducing this issue (building lmdb-js on node:18-alpine, but worked without error):
https://github.com/kriszyp/lmdb-js/runs/7082099710?check_suite_focus=true
I also output the linked deps of lmdb.node according to  `readelf -d`, which are:
```
0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
0x0000000000000001 (NEEDED)             Shared library: [libc.musl-x[8]
```
I would think that attempting to load ld-linux-x86-64.so.2 as a shared library would indicate that it had been recompiled for glibc. And I am just a dep auth, but I don't think anything in parcel should _ever_ be compiled on a standard alpine box (certainly not lmdb), we include prebuilt binaries for all standard alpine/node configs, and we only have compilation fallbacks in case you try to run it on something really weird/ancient like 32-bit win or powerpc. You may get a more accurate error message by enforcing that with `npm install --ignore-scripts` to ensure you never trigger any compilation (you might also make sure you don't install gcc, g++, etc. to ensure you never do any compilation as well). Also, just to verify, what version of parcel (or lmdb-js) are you using?

**Comment by hood** [comment]
I **had** to run `RUN apk add --update gcc g++ make python3` and then `gcompat` in order for my installation to not break, can't even remember what the issue was... something related to `node-gyp`... All this until I tried again today, when my Docker build succeeds without installing those deps :facepalm: .

 > so, just to verify, what version of parcel (or lmdb-js) are you using?

 2.6.2

**Comment by kriszyp** [comment]
Just to clarify, does this mean parcel now successfully builds your app (is the issue resolved), or that you can now install parcel, but you are still get some error (or same error)?

**Comment by hood** [comment]
The issue is now solved.

**Comment by coding-CEO** [comment]
@hood 
Did you get `npm ERR! signal SIGSEGV` this error after applying `gcompat`. If Yes, How did you fix it ??

**Comment by bb-sachinkumar** [comment]
@coding-CEO did you get solution to SIGSEGV?

**Comment by drilonibrahimi** [comment]
> @hood Did you get `npm ERR! signal SIGSEGV` this error after applying `gcompat`. If Yes, How did you fix it ??

@coding-CEO  any solution to this? I just ran into this issue!

**Comment by vinil-prabhu** [comment]
@coding-CEO @hood @drilonibrahimi @bb-sachinkumar  any solution for `SIGSEGV` error
